# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_terms', models.TextField(blank=True)),
                ('privacy_info_terms', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='ads_agree',
            field=models.BooleanField(default=False),
        ),
    ]
