# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160424_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texts',
            name='privacy_info_terms',
        ),
        migrations.RemoveField(
            model_name='texts',
            name='regist_terms',
        ),
        migrations.AddField(
            model_name='texts',
            name='contents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='texts',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
