# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(max_length=30, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=30, unique=True)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=30, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.CharField(blank=True, max_length=100)),
                ('image0', models.ImageField(blank=True, upload_to='')),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('image4', models.ImageField(blank=True, upload_to='')),
                ('image5', models.ImageField(blank=True, upload_to='')),
                ('image6', models.ImageField(blank=True, upload_to='')),
                ('image7', models.ImageField(blank=True, upload_to='')),
                ('image8', models.ImageField(blank=True, upload_to='')),
                ('image9', models.ImageField(blank=True, upload_to='')),
                ('detail', models.CharField(blank=True, max_length=100)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Brand')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='item.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.CharField(max_length=30, unique=True)),
                ('option_name', models.CharField(max_length=100)),
                ('option_price', models.IntegerField(default=0)),
                ('option_custom_price', models.IntegerField(default=0)),
                ('option_stock', models.IntegerField(default=0)),
                ('original_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
    ]
