# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20160412_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image0',
            field=models.ImageField(blank=True, upload_to=item.models.get_image_path),
        ),
    ]
