# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20160424_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemqna',
            name='answer',
            field=models.TextField(blank=True, default='<p>답변 전 입니다.</p>'),
        ),
    ]
