# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0004_auto_20160413_0507'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('cart_id', models.CharField(max_length=50)),
                ('item_price', models.IntegerField(default=0)),
                ('delivery_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('pay_price', models.IntegerField(default=0)),
                ('point_price', models.IntegerField(default=0)),
                ('point_made', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('postscript', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
